Repository TinkoffCreditSystems/gatling-picatinny, pull requests merged in 2020-10, with the labels that each got.

#12 Issue 1 refactor the profile module
  CODEOWNERS
  README.md
  project/Dependencies.scala
  project/build.properties
  src/main/scala/ru/tinkoff/gatling/config/ConfigManager.scala
  src/main/scala/ru/tinkoff/gatling/config/ProfileConfig.scala
  src/main/scala/ru/tinkoff/gatling/profile/HttpProfile.scala
  src/main/scala/ru/tinkoff/gatling/profile/Profile.scala
  src/main/scala/ru/tinkoff/gatling/profile/ProfileBuilder.scala
  src/main/scala/ru/tinkoff/gatling/profile/ProfileConfig.scala
  src/main/scala/ru/tinkoff/gatling/profile/RequestConfig.scala
  src/main/scala/ru/tinkoff/gatling/profile/http/HttpProfileConfig.scala
  src/main/scala/ru/tinkoff/gatling/profile/http/HttpRequestComponents.scala
  src/main/scala/ru/tinkoff/gatling/profile/http/HttpRequestConfig.scala
  src/main/scala/ru/tinkoff/gatling/profile/http/package.scala
  src/test/scala/ru/tinkoff/gatling/profile/ProfileSpec.scala
Labels: enhancement

#19 handle exceptions when influxdb is not available
  README.md
  src/main/scala/ru/tinkoff/gatling/influxdb/AnnotationManager.scala
  src/main/scala/ru/tinkoff/gatling/influxdb/InfluxUtils.scala
  src/test/scala/ru/tinkoff/gatling/influxdb/InfluxMock.scala
  src/test/scala/ru/tinkoff/gatling/influxdb/InfluxUtilsSpec.scala
Labels: bug

#28 fix: Fix Gatling configs for 3.4.1
  project/Dependencies.scala
  src/main/scala/ru/tinkoff/gatling/config/ConfigManager.scala
  src/main/scala/ru/tinkoff/gatling/influxdb/AnnotationManager.scala
Labels: bug, refactoring

#32 Change Dependencies scopes
  build.sbt
  project/Dependencies.scala
  project/plugins.sbt
  publish.sbt
Labels: bug, enhancement

#33 add key publish step to CI
  .travis.yml
Labels: bug
