Repository TinkoffCreditSystems/gatling-picatinny, pull requests merged in 2021-03, with the labels that each got.

#35 Change Dependencies scopes
  README.md
  example/src/test/scala/ru/tinkoff/load/example/SampleSimulation.scala
  project/Dependencies.scala
  publish.sbt
  src/test/scala/ru/tinkoff/gatling/feeders/FeedersBaseSpec.scala
  src/test/scala/ru/tinkoff/gatling/influxdb/InfluxMock.scala
Labels: enhancement

#39 add additional ci for test compile
  .github/workflows/scala.yml
  .github/workflows/test.yml
Labels: ci/cd

#41 refactor module influxdb with scala client library
  .gitignore
  build.sbt
  project/Dependencies.scala
  src/main/resources/influx-default.conf
  src/main/scala/ru/tinkoff/gatling/influxdb/AnnotationManager.scala
  src/main/scala/ru/tinkoff/gatling/influxdb/Annotations.scala
  src/main/scala/ru/tinkoff/gatling/influxdb/InfluxPersistent.scala
  src/main/scala/ru/tinkoff/gatling/influxdb/InfluxUtils.scala
  src/main/scala/ru/tinkoff/gatling/influxdb/package.scala
  src/test/scala/ru/tinkoff/gatling/influxdb/AnnotationManagerSpec.scala
  src/test/scala/ru/tinkoff/gatling/influxdb/InfluxDbMocks.scala
  src/test/scala/ru/tinkoff/gatling/influxdb/InfluxMock.scala
  src/test/scala/ru/tinkoff/gatling/influxdb/InfluxPersistentSpec.scala
  src/test/scala/ru/tinkoff/gatling/influxdb/InfluxUtilsSpec.scala
Labels: refactoring

#44 Custom influx points
  README.md
  example/src/test/resources/influx.conf
  src/main/scala/ru/tinkoff/gatling/influxdb/AnnotationManager.scala
  src/main/scala/ru/tinkoff/gatling/influxdb/Annotations.scala
  src/main/scala/ru/tinkoff/gatling/influxdb/InfluxPersistent.scala
Labels: enhancement
